use Team21_db;

DROP TABLE IF EXISTS User_Org;

DROP TABLE IF EXISTS DriverApp;

DROP TABLE IF EXISTS Item;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS PassChange;

DROP TABLE IF EXISTS AppStat;

DROP TABLE IF EXISTS Logon;

DROP TABLE IF EXISTS PointChange;

DROP TABLE IF EXISTS NewUser;

DROP TABLE IF EXISTS PointRule;

DROP TABLE IF EXISTS Reason;

DROP TABLE IF EXISTS Sponsor;

DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS Car;

DROP TABLE IF EXISTS Driver;

DROP TABLE IF EXISTS Company;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS About;

DROP TABLE IF EXISTS BadLogin;